# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0002_burner_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBurner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmed_time', models.IntegerField()),
                ('programming_id', models.IntegerField()),
                ('burner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooktopper.Burner')),
                ('new_burner_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooktopper.BurnerState')),
                ('new_temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooktopper.Temperature')),
            ],
        ),
        migrations.RemoveField(
            model_name='programmingdetails',
            name='programmed_hour',
        ),
        migrations.RemoveField(
            model_name='programmingdetails',
            name='programming_type',
        ),
        migrations.AddField(
            model_name='programmingdetails',
            name='new_burner_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooktopper.BurnerState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmingdetails',
            name='programmed_time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProgrammingType',
        ),
    ]
